# QCA IPQ Sound Card Support
snd-soc-ipq-objs := ipq.o
snd-soc-ipq-cpu-dai-objs := ipq-cpu-dai.o
snd-soc-ipq-pcm-i2s-objs := ipq-pcm-i2s.o
snd-soc-ipq-pcm-tdm-objs := ipq-pcm-tdm.o
snd-soc-ipq-pcm-spdif-objs := ipq-pcm-spdif.o

obj-$(CONFIG_SND_SOC_IPQ) += ipq.o
obj-$(CONFIG_SND_SOC_IPQ_ADSS) += ipq-adss.o
obj-$(CONFIG_SND_SOC_IPQ_CPU_DAI) += snd-soc-ipq-cpu-dai.o
obj-$(CONFIG_SND_SOC_IPQ_STEREO) += ipq-stereo.o
obj-$(CONFIG_SND_SOC_IPQ_MBOX) += ipq-mbox.o
obj-$(CONFIG_SND_SOC_IPQ_PCM_I2S) += snd-soc-ipq-pcm-i2s.o
obj-$(CONFIG_SND_SOC_IPQ_CODEC) += ipq-codec.o
obj-$(CONFIG_SND_SOC_IPQ_PCM_SPDIF) += snd-soc-ipq-pcm-spdif.o
obj-$(CONFIG_SND_SOC_IPQ_PCM_TDM) += snd-soc-ipq-pcm-tdm.o
